### ISSUE TITLE
It's reporting mixins and function parameters as variables

### ISSUE THREAD

**Issue by aziz** [fChristenson/sassy-stats#6]
Consider this case

```scss
@mixin border-mobile($size, $colour) {
  border-bottom: $priceFilterBorderSize solid $colour;
}

@mixin border-desktop($size, $colour) {
  border-left: $priceFilterBorderSize solid $colour;
}
```

the `$size` and `$colour` are parameters and should not be reported as variables.
